version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch-node-browsers-legacy
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      # - image: circleci/node:8
      # - image: circleci/python:2.7-browsers
      - image: circleci/postgres:9.6.5-alpine-ram
    parallelism: 4 

    working_directory: ~/devTings

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo apt-get update 
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "SELECT current_database();"
      - run: sudo npm install knex -g
      - run: knex --version
      - run: 'knex migrate:latest'
      # - run: |
      #     psql \
      #     -d $TEST_DATABASE_URL \
      #     -c "select * from information_schema.tables"
      - run: 'knex seed:run'
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "select * from users"
      - run: 
          name: yarn start
          command: yarn start
          background: true
      - run: 
          name: 'Install taurus'
          command: 'sudo pip install bzt'
      - run: 
          name: 'Initiate benchmark test'
          command: 'bzt benchmark/scripts/poc_jmeter_2.yml -report'
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # jmeter_test: 
  #   docker:
  #     - image: circleci/openjdk:8-jdk-node-browsers

  #   working_directory: ~/devTings

  #   steps: 
  #     - checkout
  #     - run: 
  #         name: initiate benchmark test
  #         command: 'benchmark/jmeter/apache-jmeter-5.0/bin/./jmeter -n -t benchmark/scripts/poc_jmeter_2.jmx'

  # taurus_test: 
  #   docker: 
  #     - image: circleci/python:2.7-browsers

  #   working_directory: ~/devTings

  #   steps: 
  #     - checkout
  #     - run: 
  #         name: 'Install taurus'
  #         command: 'sudo pip install bzt'
  #     - run: 
  #         name: 'Initiate benchmark test'
  #         command: 'bzt benchmark/scripts/poc_jmeter_2.yml -report'
        
      #- run: 'bzt benchmark/scripts/poc_jmeter_2.yml -o modules.console.disable=true' < this is working

workflows: 
  version: 2 

  build_deploy: 
    jobs: 
      - build
      # - taurus_test
      # - taurus_test: 
      #     filters: 
      #       branches: 
      #         only: master 
      #     requires: 
      #       - build