version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
        environment: 
          LANG: en_US.UTF-8

    working_directory: ~/devTings

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # jmeter_test: 
  #   docker:
  #     - image: circleci/openjdk:8-jdk-node-browsers

  #   working_directory: ~/devTings

  #   steps: 
  #     - checkout
  #     - run: 
  #         name: initiate benchmark test
  #         command: 'benchmark/jmeter/apache-jmeter-5.0/bin/./jmeter -n -t benchmark/scripts/poc_jmeter_2.jmx'

  taurus_test: 
    docker: 
      - image: circleci/python:2.7-browsers

    working_directory: ~/devTings

    steps: 
      - checkout
      - run: 
          name: 'Install taurus'
          command: 'sudo pip install bzt'
      - run: 
          name: 'Initiate benchmark test'
          command: 'bzt benchmark/scripts/poc_jmeter_2.yml -report'


      #- run: 'bzt benchmark/scripts/poc_jmeter_2.yml -o modules.console.disable=true' < this is working

workflows: 
  version: 2 

  build_deploy: 
    jobs: 
      - build
      - taurus_test: 
          filters: 
            branches: 
              only: master 
          requires: 
            - build