version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch-node-browsers-legacy
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      # - image: circleci/node:8
      # - image: circleci/python:2.7-browsers
      - image: circleci/postgres:9.6.5-alpine-ram
    parallelism: 4 

    working_directory: ~/devTings

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
          name: 'Install Database'
          command: |
            sudo apt-get update 
            sudo apt-get install postgresql-client-9.6
      - run: 
          name: 'Setup Database'
          command: |
            sudo npm install knex -g
            knex migrate:latest
            knex seed:run
      - run: 
          name: 'Start Application'
          command: yarn start
          background: true
      - run: 
          name: 'Install taurus'
          command: 'sudo pip install bzt'
      - run: 
          name: 'Initiate benchmark test'
          command: 'bzt benchmark/scripts/poc_jmeter_2.yml'
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

    #command: 'benchmark/jmeter/apache-jmeter-5.0/bin/./jmeter -n -t benchmark/scripts/poc_jmeter_2.jmx'

workflows: 
  version: 2 

  build_deploy: 
    jobs: 
      - build
      # - taurus_test: 
      #     filters: 
      #       branches: 
      #         only: master 
      #     requires: 
      #       - build