version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/devTings

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  benchmark_test: 
 
      # - run: 
      #   name: 'sudo apt-get update'
      # - run: 'java -version'
      # - run: 'sudo add-apt-repository ppa:openjdk-r/ppa'
      # - run: sudo apt-get update 
      # - run: sudo apt-get install openjdk-8-jdk
      # - run: 'java -version'
      # - run: 'sudo apt-get install openjdk-7-jre-headless'
      # - run: 'wget -c http://ftp.ps.pl/pub/apache//jmeter/binaries/apache-jmeter-5.0.tgz'
      # - run: 'ls -al'
      # - run: 'tar xzf apache-jmeter-5.0.tgz'
      # - run: 'ls -al'
      # - run: 
      #     name: 
      #     command: 'cd apache-jmeter-5.0'
      # - run: 'apache-jmeter-5.0/bin/./jmeter'
      #  - run: 'ls -al'
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers

    working_directory: ~/devTings

    steps: 
      - run: 
          name: run load
          command: 'apache-jmeter-5.0/bin/./jmeter -n -t poc_jmeter_2.jmx'

      # # run tests!
      # - run: yarn test
workflows: 
  version: 2 

  build_deploy: 
    jobs: 
      - build
      - benchmark_test: 
        branches: master 
        requires: 
          -build